
The purpose of these scripts is to extract extreme discharges (high and low streamflow) from two periods (typically 30-years) corresponding to a transient period (the global mean temperature is increasing with time) and a quasi-equilibrium period (the global mean temperature is relatively stable). The global mean temperature (30-year average) is identical between the two climates.
We then assessed whereas a statistical difference between the extreme streamflow series gathered for the two climates could be observed. Some important features of the study include:
- Use of multiple GCMs
- Use of multiple Global Water Model (GWM)

A brief description of each script is provided below, explaning what the code does, what are the required input and what are the produced outputs. Note that additional information is generally given within every script, in the form of comments and at the beginning of the files.

* Main scripts
** 1.0_main_analysis.r
*** General purpose
This script first extract, yearly, the extreme streamflow for two periods for a given GWM and GCM. Then, the two series of extreme streamflow are compared using a K-S test. 
- About 70% of the script is just for reading the correct netcdf file depending on the period and experiment specified.
*** I/O
- Inputs: GWM (string), GCM (string), Experiment1 (string), Experiment2 (string), Period1 (start end), Period2 (start end), Permutation (yes/no)

- Outputs:
  - Binary files containing the gridded 30 extreme streamflows to avoid reading the daily netcdf again.
  - Outputs from the K-S test:
    - test statistics.
    - test p value.
  - If permutation is activated, 1000 bootstrap is used to evaluate again the K-S test statistic.
    - Report 95th percentile.
  - Gumbel ditributions are fitted to the extreme series
    - Separatly for all indices and climate periods
    - The parameters (2) of the gumbel distribution are saved

*** Caveats
- Largely comply with Lintr
** 1.1_pi_control.sh
*** General purpose
A simple shell script that launches the previous script (1.0) for a given picontrol simulation.
- Immediatly launches all GCM and GWM combinations.

*** I/0
- Same as Script 1.0

*** Caveats
- None

** 2.0_summarise.r
*** General purpose
This script use the output of the previous script to assess the percentage of global land surface where a significnat difference in extreme discharge was indentified. The script the files created for all combinations of GCMs and GWMs and then perform various levels of aggregation.

*** I/O
- Inputs: The binary files containing the result of the K-S test.

- Outputs: Four csv files:
  - All ensemble
  - GCM aggregation
  - GWM aggregation
  - The raw input data for all GWM and GCM concatenated and cleaned-up by removing ocean and sea. 

*** Caveats
- Largely comply with Lintr
- Wilk's FDR adjustment is implemented

** 2.1_summarise_pi.r
*** General purpose
Identical as the script above but here only for reading pi-control simulations
*** I/O
- Inputs: The binary files containing the result of the K-S test.

- Outputs: two scv files:
  - A general file summarising the 95th percentile range of global land surface where a significant difference in extreme streamflow can be observed for all GWM, GCM and iteration.
  - Same as above but no iteration, the complete range is reported

*** Caveats
- Largely comply with Lintr

** 2.2_all_combinations_ghm-gcm.r
*** General purpose
This script evaluate the consensus toward significant difference in extreme streamflow amon an ensemble for all possible ensemble possible. The total number of combination is: 8^6-1 = 262143.
- 6 GHMs
- 8 choices for every of them:
  - not used
  - hadgem2-es
  - ipsl-cm5a-lr
  - miroc5
  - hadgem2-es and ipsl-cm5-lr
  - hadgem2-es and miroc5
  - ipsl-cm5-lr and miroc5
  - hadgem2-es and ipsl-cm5-lr and miroc5
A single combination need to be remove as it consist of the combination where all gcm are turned off.

*** I/O
- Inputs: 
  - A single csv file which indicates the cells where the extreme streamflow where significantly different between the transient and quasi-equilibrium climates
  - For all ghm and gcm
    
- Outputs: a csv file called "all_combinations.csv". It contains the fraction of grid cell where at least 66% of the ensemble agree that there are significant difference in extreme streamflow.

*** Caveats
- Comply with Lintr

** 3.0_basin.r
*** General purpose
For given basins (indicated in the basins_id variable), extract the extreme streamflow for the transient and quasi-equilibrium climates.

*** I/O
- Inputs:
  - H08 files relevant to river network and basins
    - Carefull the endian is different for these files (big).
  - Extreme binary files (created in script 1)
  - Result of K-S test (created in script 1)

- Outputs: A csv file containing the extreme streamflow at the mouth of the basin.

*** Caveats
- Largely comply with Lintr
- The basins are hard coded and currently include: Amazon, Congo, Niger, and Murray

** 3.1_basin_dly_flow.r
*** General purpose
Similar to previous script but only for daily streamflow for the transient and quasi-equilibrium periods.

*** I/O
- Inputs: Original netcdf fiel from ISIMIP.

- Outputs: One csv file which is appended with the daily flow.

*** Caveats
- Largely comply with Lintr

** 4.0_qq_and_0_count_assessment.r
*** General purpose
Report the number of zero flow in low flow and the slope of the Q-Q plot for high streamflow.

*** I/O
- Inputs: The binary files from script 1.

- Outputs: Two csv files for low and high flows.
  - Note that for a given GWM all dat is pulled toguether hence 1 file per GWMs

*** Caveats
- Largely comply to Lintr

** 4.1_post_qq_and_null_flow.r
*** General purpose
Report the fraction of zero flow for low flow and the cells which slope of the Q-Q plot for high streamflow is "strange".

*** I/O
- Inputs: The csv files created in script 4.0

- Outputs: Two scv files, one for low streamflow, the other for high streamflow.

*** Caveats
- Largely comply with Lintr

* Tables and Figures
** 0_histogram.r
*** General purpose
To create the historgrams in Fig. 1

*** Caveats
- Largely comply with Lintr

** 0_temperature_trend.r
*** General purpose
Create Figure 1 and identify the transient and quasi-equilibrium periods

*** I/O
- Inputs

- Outputs: Figure 1 (a and b)

*** Caveats
- Largely comply with Lintr

** 1_combined_maps.r
*** General purpose
*** I/O
*** Caveats

** 1_maps_qq_and_0_flows.r
*** General purpose
*** I/O
*** Caveats

** 1.5_
*** General purpose
*** I/O
*** Caveats

** 
