
The purpose of these scripts is to extract extreme discharge (high and low flow) from two periods (30 years) corresponding to atransient period () and a stabilized period () for which the global mean temperature is identical.
Then we assessed whereas a statistical difference could be observed betweent the extreme series obtained for both climate. Multiple GCMs and GHm are used and these script aggregate the data at the grid cell, GHM, indices, and GCM level. 

* Main scripts
- 1_main_analysis.r: In this script, a model (e.g. H08, WaterGAP2...), a GCM (hadgem2-es, miroc5...) are first given. Then 2 experiments (hist, rcp26...)  and corresponding period (usually 30 years 1661 1690 for example) need to be defined. The script will run if the period in not 30year but some analysis wll be incorrect. The script can be devided into 3 parts, first the annual daily discharge is read and converted to high and low glow indices. Second a statistical test is done for all grid cell and the result of this test is saved. Third the extrema series are fitted to a gumble distribution and that distribution is used to extram th extrama expected with 1/100 probability or once every 100 year. That data and the gumbel parameter are also saved.

- 2_summarise.r: This script read an input that was generated by the previous script and simply aggregate the data. it ouputs a simplified table that give overall and for every models the percentage of land grid cell where a statistical difference was observed between the transient and stabilize climates.

- 3_diffrences_100y.r: This scrpt reads the file generated in the tird step of script 1. Again data is aggregated here at the grid cell level. For every grid cell we whant to know the difference in extrema expected once in a 100 year between the transient and stabilized climates. Aggregated result are output and can be easily process on a personal computer.
